# Generated by Django 3.2.13 on 2024-01-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('semester_year', models.CharField(max_length=20)),
                ('instructors', models.CharField(max_length=100)),
                ('class_schedule', models.CharField(max_length=100)),
                ('textbooks_materials', models.TextField()),
                ('assessment_methods_syllabus', models.TextField()),
            ],
        ),
    ]
