# Generated by Django 3.2.13 on 2024-01-20 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='instructors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faculty'),
        ),
    ]
