# Generated by Django 3.2.13 on 2024-01-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subject_class_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classschedule',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='classschedule',
            name='date',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(default='09:30'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(default='08:00'),
        ),
    ]
