# Generated by Django 5.0.1 on 2024-08-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_student"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ClassSchedule",
            new_name="ProjectSchedule",
        ),
        migrations.CreateModel(
            name="project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_id", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("department", models.CharField(max_length=50)),
                ("semester_year", models.CharField(max_length=20)),
                ("textbooks_materials", models.TextField()),
                ("assessment_methods_syllabus", models.TextField()),
                (
                    "instructors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.faculty"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.student"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="projectschedule",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.project"
            ),
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
