# Generated by Django 5.0.1 on 2024-08-24 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_rename_classschedule_projectschedule_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectschedule",
            name="subject",
        ),
    ]
